services:
  db:
    image: mariadb:10.6
    container_name: mariadb-wp
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_pw
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD_FILE: /run/secrets/db_user_pw
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_user_pw
      - db_root_pw
    networks:
      - backend
    restart: unless-stopped

  wordpress:
    depends_on:
      - db
    image: wordpress:php8.2-fpm
    container_name: wordpress
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_user_pw
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://localhost:8443');
        define('WP_SITEURL', 'https://localhost:8443');
        define('FORCE_SSL_ADMIN', true);
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - db_user_pw
    networks:
      - backend
      - frontend
    restart: unless-stopped

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ABSOLUTE_URI: https://localhost:8443/phpmyadmin/
    networks:
      - backend
      - frontend
    restart: unless-stopped

  nginx:
    depends_on:
      - wordpress
    image: nginx:alpine
    container_name: nginx-wp
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    networks:
      - frontend
    restart: unless-stopped

secrets:
  db_user_pw:
    file: secrets/db_password.txt
  db_root_pw:
    file: secrets/db_root_password.txt

volumes:
  db_data:
  wordpress_data:

networks:
  frontend:
  backend:
