services:
  db:
    image: mariadb:10.6
    container_name: mariadb-wp-1
    environment:
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/db_root_pw
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD_FILE: /run/secrets/db_user_pw
    volumes:
      - db_data:/var/lib/mysql
    secrets:
      - db_user_pw
      - db_root_pw
    networks:
      - backend

  wordpress:
    depends_on:
      - db
    image: wordpress:fpm
    container_name: wordpress-fpm-1
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD_FILE: /run/secrets/db_user_pw
    volumes:
      - wordpress_data:/var/www/html
    secrets:
      - db_user_pw
    networks:
      - backend
      - frontend

  nginx:
    depends_on:
      - wordpress
    image: nginx:alpine
    container_name: nginx-1
    ports:
      - "8080:80"
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - frontend

secrets:
  db_user_pw:
    file: secrets/db_password.txt
  db_root_pw:
    file: secrets/db_root_password.txt

volumes:
  db_data:
  wordpress_data:

networks:
  frontend:
  backend:
